server:
  port: 9001
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/ #多个Eurekaserver之间用","隔开
  instance:
    prefer-ip-address: true #使用ip地址进行注册
name: handpro