server:
  port: 7004
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjw1635596002/config-server.git
          
