server:
  port: 6001
spring:
  application:
    name: server-shopclient
  rabbitmq: 
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
feign:
  client:
    config:
      server-shop:
        Logger:
          LoggerLevel: full
  hystrix: #开启熔断
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
