server:
  port: 8000
spring:
  application:
    name: service-shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ #多个Eurekaserver之间用","隔开
  instance:
    prefer-ip-address: true #使用ip地址进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
name: handproduct-qweq
